### ISSUE TITLE
1.13.2 support

### ISSUE THREAD

**Issue by adiantek** [games647/LogIt#4]
This plugin doesn't work on 1.13.2 version:

```
[21:20:32 INFO]: [LogIt] Enabling LogIt vSNAPSHOT*
[21:20:32 WARN]: [LogIt] LogIt does not support this version of Bukkit. Some features may not work.
[21:20:32 ERROR]: Error occurred while enabling LogIt vSNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: org.sqlite.JDBC.createConnection(Ljava/lang/String;Ljava/util/Properties;)Ljava/sql/Connection;
        at io.github.lucaseasedup.logit.storage.SqliteStorage.connect(SqliteStorage.java:27) ~[?:?]
        at io.github.lucaseasedup.logit.storage.WrapperStorage.connect(WrapperStorage.java:40) ~[?:?]
        at io.github.lucaseasedup.logit.LogItCore.setUpAccountManager(LogItCore.java:531) ~[?:?]
        at io.github.lucaseasedup.logit.LogItCore.start(LogItCore.java:251) ~[?:?]
        at io.github.lucaseasedup.logit.LogItPlugin.onEnable(LogItPlugin.java:77) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-474]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-474]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-474]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

```

**Comment by sgdc3** [comment]
Have you considered moving to AuthMeReloaded? It is constantly updated.
